// Generated by https://quicktype.io

export interface Resume {
    $schema:      string;
    basics:       Basics;
    work:         Work[];
    volunteer:    any[];
    education:    Education[];
    awards:       any[];
    certificates: Certificate[];
    publications: Publication[];
    skills:       Skill[];
    languages:    Language[];
    interests:    any[];
    references:   Reference[];
    projects:     any[];
    meta:         Meta;
}

export interface Basics {
    name:     string;
    label:    string;
    image:    string;
    email:    string;
    phone:    string;
    url:      string;
    summary:  string;
    location: Location;
    profiles: Profile[];
}

export interface Location {
    countryCode: string;
    address:     string;
}

export interface Profile {
    network:  string;
    username: string;
    url:      string;
}

export interface Certificate {
    name:       string;
    issuer:     string;
    startDate?: string;
    url?:       string;
}

export interface Education {
    institution: string;
    area:        string;
    studyType:   string;
    startDate:   string;
    endDate:     string;
    score:       string;
    courses:     any[];
}

export interface Language {
    fluency:  string;
    language: string;
}

export interface Meta {
    theme:     string;
    version:   string;
    canonical: string;
}

export interface Publication {
    name:        string;
    publisher:   string;
    releaseDate: string;
    summary:     string;
    url:         string;
}

export interface Reference {
    name:      string;
    reference: string;
}

export interface Skill {
    name:     string;
    level:    string;
    keywords: any[];
}

export interface Work {
    name:       string;
    position:   string;
    startDate:  string;
    endDate:    string;
    summary?:   string;
    highlights: string[];
    url:        string;
    location?:  string;
}
